### PR TITLE
Added default blueprint which includes the bower package dep

### PR DESCRIPTION
**Pull request by pfmmfp**

### CODE REVIEW

**Review by morhook — APPROVED** [review]
This looks good!!

**Comment by morhook** [comment]
What's wrong with this guy 'bitHound'? Looks like it's failing on a dependency that ember should upgrade (ember-load-initializers), first not our addon.

**Comment by pfmmfp** [comment]
Yeah, I will remove that integration as it's not really useful for this skinny repo.

**Comment by morhook** [comment]
Poor guy 'gitHound', now I feel sorry.

**Pull request merged**
